# Generated by Django 5.0.6 on 2024-06-09 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=155)),
                ('placa', models.CharField(max_length=155)),
                ('cantAsientos', models.IntegerField()),
                ('año', models.IntegerField(blank=True, null=True)),
                ('operativo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placa', 'año', 'modelo'],
            },
        ),
    ]
