# Generated by Django 5.0.6 on 2024-07-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created_by',
        ),
    ]
