# Generated by Django 5.0.6 on 2024-06-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('Ruc', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Dirección', models.CharField(max_length=255)),
                ('Contacto', models.IntegerField()),
            ],
        ),
    ]
