# Generated by Django 5.0.6 on 2024-06-09 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0002_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Dirección',
            new_name='Adress',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Contacto',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Nombre',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='id_empresa',
            new_name='id',
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('DNI', models.IntegerField()),
                ('Teléfono', models.IntegerField()),
                ('FechaViaje', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='aplicacionComprobanteTransporte.empresa')),
            ],
        ),
    ]
