# Generated by Django 5.0.6 on 2024-07-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0002_remove_cliente_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='TravelDate',
        ),
    ]
