# Generated by Django 5.0.6 on 2024-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0002_ruta_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
