# Generated by Django 5.0.6 on 2024-06-09 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0003_rename_dirección_empresa_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Teléfono',
            new_name='Cellphone',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellidos',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='FechaViaje',
            new_name='TravelDate',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='empresa',
            new_name='id_company',
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
