# Generated by Django 5.0.6 on 2024-06-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0004_rename_teléfono_cliente_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['license_plate', 'year', 'model']},
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='placa',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='operativo',
            new_name='operational',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='cantAsientos',
            new_name='seats',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='año',
            new_name='year',
        ),
    ]
