# Generated by Django 5.0.6 on 2024-06-10 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0006_cliente_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('surName', models.CharField(max_length=155)),
                ('DNI', models.IntegerField(blank=True, default=0, null=True)),
                ('adress', models.CharField(max_length=155)),
                ('phoneNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('licenseType', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'surName', 'DNI'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startingPlace', models.CharField(max_length=155)),
                ('destinationPlace', models.CharField(max_length=155)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stops', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drivers', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='aplicacionComprobanteTransporte.conductor')),
                ('vehicles', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='aplicacionComprobanteTransporte.vehiculo')),
            ],
            options={
                'ordering': ['startingPlace', 'destinationPlace', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionComprobanteTransporte.cliente')),
            ],
        ),
    ]
