# Generated by Django 5.0.6 on 2024-06-10 02:28

import aplicacionComprobanteTransporte.models.ruta
import aplicacionComprobanteTransporte.models.voucher
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0007_conductor_ruta_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientData', models.CharField(max_length=100, verbose_name=aplicacionComprobanteTransporte.models.ruta.Ruta)),
                ('DNI', models.CharField(max_length=100, verbose_name=aplicacionComprobanteTransporte.models.voucher.Voucher)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
