# Generated by Django 5.0.6 on 2024-06-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0008_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ClientData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionComprobanteTransporte.ruta'),
        ),
        migrations.AlterField(
            model_name='details',
            name='DNI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionComprobanteTransporte.voucher'),
        ),
    ]
