# Generated by Django 5.0.6 on 2024-06-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionComprobanteTransporte', '0009_alter_details_clientdata_alter_details_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='DNI',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='DNI',
            new_name='Name',
        ),
    ]
